# Generated by Django 5.2.6 on 2026-01-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TradeJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("buy_date", models.DateField(blank=True, null=True)),
                ("strategy", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "entry_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pyramiding", models.CharField(blank=True, max_length=50, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "buy_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "broker_commission",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("sebon_fee", models.DecimalField(decimal_places=2, max_digits=8)),
                ("dp_charge", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "capital_gain_tax",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "profit_loss_rs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "profit_loss_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("emotions_entry", models.TextField(blank=True, null=True)),
                ("emotions_exit_profit", models.TextField(blank=True, null=True)),
                ("emotions_exit_sl", models.TextField(blank=True, null=True)),
                ("learning", models.TextField(blank=True, null=True)),
                ("mistakes", models.TextField(blank=True, null=True)),
                (
                    "rating_execution",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("chart_link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
